apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/myfoodie-microservice-default: "true"
        io.kompose.service: discovery-server
    spec:
      containers:
        - env:
            - name: management.zipkin.tracing.endpoint
              value: http://zipkin:9411/api/v2/spans
          image: abdullahiisse/discovery-server:latest
          name: discovery-server
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
