apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/myfoodie-microservice-default: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka:password@discovery-server:8761/eureka
            - name: management.zipkin.tracing.endpoint
              value: http://zipkin:9411/api/v2/spans
            - name: spring.datasource.password
              value: Password!
            - name: spring.datasource.url
              value: jdbc:postgresql://myfoodiedb.postgres.database.azure.com:5432/MyFoodieUserService
            - name: spring.datasource.username
              value: myfoodie@myfoodiedb
          image: abdullahiisse/user-service:latest
          name: user-service
          ports:
            - containerPort: 35045
              hostPort: 35045
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
