# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myfoodie-discovery-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfoodiediscoveryserver.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8eeac65c802d41688f8b83a1d31d9b0c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_033d47c2fcb84551b9f153240451f2ac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfoodiediscoveryserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8eeac65c802d41688f8b83a1d31d9b0c }}/discovery-server:${{ github.sha | lower }}
        file: ./discovery-server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myfoodie-discovery-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f1af92f47be4a489060f00d84e66686 }}
        images: 'myfoodiediscoveryserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8eeac65c802d41688f8b83a1d31d9b0c }}/discovery-server:${{ github.sha }}'
