# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myfoodie-favorite-dish-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfoodiefavoritedishservice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bcc54fb30a0f4561b975ffbbcdd38d3e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c0aaea2be87a46959569b9203bdac2dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfoodiefavoritedishservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcc54fb30a0f4561b975ffbbcdd38d3e }}/favoritedishservice:${{ github.sha }}
        file: ./favorite-dish-service/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myfoodie-favorite-dish-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aef63030d182440bbb96ecbef97d258e }}
        images: 'myfoodiefavoritedishservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcc54fb30a0f4561b975ffbbcdd38d3e }}/favoritedishservice:${{ github.sha }}'
