# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myfoodie-calendar-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfoodiecalendarservice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6b9fda3d44d1401793c64f1c2e622a7b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b2527fd19fa470ab8cb16e2b43f7be4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfoodiecalendarservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6b9fda3d44d1401793c64f1c2e622a7b }}/calendarservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myfoodie-calendar-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4874bb23e938478098ef87cc19a6c047 }}
        images: 'myfoodiecalendarservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6b9fda3d44d1401793c64f1c2e622a7b }}/calendarservice:${{ github.sha }}'