# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myfoodie-user-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfoodieuserservice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_39e1e19b759049ab9b69ed4ae54ee6f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1918b1a2e836404dbe8839daa0e4c02c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfoodieuserservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_39e1e19b759049ab9b69ed4ae54ee6f7 }}/userservice:${{ github.sha }}
        file: ./user-service/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myfoodie-user-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf1559534cad4a13845378fc4ae48ce1 }}
        images: 'myfoodieuserservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_39e1e19b759049ab9b69ed4ae54ee6f7 }}/userservice:${{ github.sha }}'
